[theme]
primaryColor = "#64ffda"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2130"
textColor = "#ccd6f6"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
